### POST TEST
POST http://localhost:8080/api/v2/members
Content-Type: application/json

{
  "name":"test"
}

### PUT TEST
PUT http://localhost:8080/api/v2/members/1
Content-Type: application/json

{
"name":"new-name"
}

### v1 회원 전체 조회
GET http://localhost:8080/api/v1/members
Content-Type: application/json

### v2 회원 전체 조회
GET http://localhost:8080/api/v2/members
Content-Type: application/json